#pragma once

// #define BT_RUNNING 0
// #define BT_SUCCESS 1
// #define BT_FAILURE -1
// #define BT_SKIP -2

#define BT_INTERNAL_STATUS_UNTICKED 0
#define BT_INTERNAL_STATUS_TICKED 1
#define BT_INTERNAL_STATUS_COMPLETED 2

#define ST_INTERNAL_STATUS_INACTIVE 0
#define ST_INTERNAL_STATUS_ACTIVE 1